import type { BikeStatus, BikeType, RideLevel } from "@/lib/types";

export const BIKE_STATUSES: BikeStatus[] = [
  "En Regla",
  "Robada",
  "Transferida",
];

export const APP_NAME = "BiciRegistro";
export const SITE_URL = "https://biciregistro.mx";

export const MEXICAN_STATES: string[] = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Coahuila",
  "Colima",
  "Ciudad de México",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "México (Estado de)",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
];

export const LAT_AM_LOCATIONS: Array<{ country: string; states: string[] }> = [
  {
    country: "México",
    states: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Ciudad de México",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "México (Estado de)",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ],
  },
  {
    country: "Argentina",
    states: [
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucumán",
    ],
  },
  {
    country: "Colombia",
    states: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlántico",
      "Bogotá D.C.",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Caquetá",
      "Casanare",
      "Cauca",
      "Cesar",
      "Chocó",
      "Córdoba",
      "Cundinamarca",
      "Guainía",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Putumayo",
      "Quindío",
      "Risaralda",
      "San Andrés y Providencia",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cauca",
      "Vaupés",
      "Vichada",
    ],
  },
  {
    country: "Chile",
    states: [
      "Aisén",
      "Antofagasta",
      "Araucanía",
      "Arica y Parinacota",
      "Atacama",
      "Biobío",
      "Coquimbo",
      "Los Lagos",
      "Los Ríos",
      "O'Higgins",
      "Magallanes",
      "Maule",
      "Metropolitana de Santiago",
      "Ñuble",
      "Tarapacá",
      "Valparaíso",
    ],
  },
  {
    country: "Perú",
    states: [
      "Amazonas",
      "Áncash",
      "Apurímac",
      "Arequipa",
      "Ayacucho",
      "Cajamarca",
      "Callao",
      "Cusco",
      "Huancavelica",
      "Huánuco",
      "Ica",
      "Junín",
      "La Libertad",
      "Lambayeque",
      "Lima",
      "Loreto",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Piura",
      "Puno",
      "San Martín",
      "Tacna",
      "Tumbes",
      "Ucayali",
    ],
  },
];

export const GENDERS: Array<{
  value: "masculino" | "femenino" | "otro" | "prefiero_no_decir" | "";
  label: string;
}> = [
  { value: "masculino", label: "Masculino" },
  { value: "femenino", label: "Femenino" },
  { value: "otro", label: "Otro" },
  { value: "prefiero_no_decir", label: "Prefiero no decir" },
];

export const RIDE_LEVELS: Array<{ value: RideLevel; label: string }> = [
  { value: "Principiante", label: "Principiantes" },
  { value: "Intermedio", label: "Intermedios" },
  { value: "Experto", label: "Expertos" },
];

export const BIKE_TYPES: Array<{ value: BikeType; label: string }> = [
  { value: "Ruta", label: "Ruta" },
  { value: "Pista", label: "Pista" },
  { value: "Enduro", label: "Enduro" },
  { value: "XC", label: "XC (Cross Country)" },
  { value: "Downhill", label: "Downhill" },
  { value: "BMX", label: "BMX" },
  { value: "Trial", label: "Trial" },
  { value: "Gravel", label: "Gravel" },
  { value: "Urbana", label: "Urbana" },
  { value: "E-Bike", label: "E-Bike" },
];

export const DAYS_OF_WEEK = [
  { id: "Lunes", label: "L" },
  { id: "Martes", label: "M" },
  { id: "Miércoles", label: "X" },
  { id: "Jueves", label: "J" },
  { id: "Viernes", label: "V" },
  { id: "Sábado", label: "S" },
  { id: "Domingo", label: "D" },
];

export const PLACEHOLDER_NONE_VALUE = "_PLACEHOLDER_NONE_";

export const OTHER_BRAND_VALUE = "Otra";
export const BIKE_BRANDS: string[] = [
  "Trek",
  "Specialized",
  "Giant",
  "Cannondale",
  "Scott",
  "Santa Cruz",
  "Yeti",
  "Cervélo",
  "Pinarello",
  "Bianchi",
  "Orbea",
  "Canyon",
  "Cube",
  "Merida",
  "Belfort",
  "Turbo",
  "Benotto",
  "Alubike",
  "Fuji",
  "Kona",
  "GT",
  "Schwinn",
  "Marin",
  "Norco",
  "Rocky Mountain",
  "Salsa",
  "Surly",
];
